add retry functionality for transient rsync errors

diff --git a/assets/in b/assets/in
--- a/assets/in
+++ b/assets/in
@@ -10,6 +10,9 @@ echo $ATC_EXTERNAL_URL 1>&2
 
 PLATFORM=`uname`
 
+MAX_RETRIES=10
+SLEEP_TIME=10
+
 SCRIPT_INPUT='/tmp/input'
 cat > $SCRIPT_INPUT <&0 # STDIN params
 
@@ -67,14 +70,38 @@ if [ "$skip_download" = "false" ]; then
         RSYNC_CMD="rsync -Pav -e 'ssh -i ~/.ssh/server_key -p $PORT' $USER@$SERVER:$SRC_DIR/* $DEST_DIR"
         echo $RSYNC_CMD  1>&2
         eval $RSYNC_CMD  1>&2
+
         if [ $? -eq 0 ]; then
             TIMESTAMP=$(find $DEST_DIR -type f -exec stat -c "%Y" {} \; | sort -n | tail -1)
             OUTPUT_STRING="{ \"version\": { \"ref\": \"$TIMESTAMP\"} }"
             echo $OUTPUT_STRING
             exit 0
-        else
-        echo "Failed to rsync $SRC_DIR to $DEST_DIR" 1>&2
-        exit 1
+        fi
+
+        i=0
+        while [ $? -ne 0 -a $i -lt $MAX_RETRIES ]
+        do
+            if [ $? -eq 0 ]; then
+                TIMESTAMP=$(find $DEST_DIR -type f -exec stat -c "%Y" {} \; | sort -n | tail -1)
+                OUTPUT_STRING="{ \"version\": { \"ref\": \"$TIMESTAMP\"} }"
+                echo $OUTPUT_STRING
+                exit 0
+            else
+                echo "Command failed - retrying in $SLEEP_TIME..."
+                sleep $SLEEP_TIME
+                i=$(($i+1))
+                eval $COMMAND
+
+                echo $RSYNC_CMD  1>&2
+                eval $RSYNC_CMD  1>&2
+            fi
+
+        done
+
+        if [ $i -eq $MAX_RETRIES ]
+        then
+            echo "Max retries reached"
+            exit 1
         fi
     else
         echo "Version $VERSION no longer available in $BASE_DIR" 1>&2
diff --git a/assets/out b/assets/out
--- a/assets/out
+++ b/assets/out
@@ -9,6 +9,10 @@ echo $BUILD_PIPELINE_NAME 1>&2
 echo $ATC_EXTERNAL_URL 1>&2
 
 PLATFORM=`uname`
+
+MAX_RETRIES=10
+SLEEP_TIME=10
+
 MD5_TOOL="md5sum"
 if [ $PLATFORM = "Darwin" ]; then
   MD5_TOOL="md5"
@@ -91,24 +95,45 @@ do
     eval $CMD 1>&2
 
     if [ $? -eq 0 ]; then
-    RSYNC_CMD="rsync $RSYNC_OPTS -e 'ssh -i ~/.ssh/server_key -p $PORT'  $SRC_DIR/$SYNC_DIR/ $USER@$SERVER:$DEST_DIR"
-    echo $RSYNC_CMD 1>&2
+        RSYNC_CMD="rsync $RSYNC_OPTS -e 'ssh -i ~/.ssh/server_key -p $PORT'  $SRC_DIR/$SYNC_DIR/ $USER@$SERVER:$DEST_DIR"
+        echo $RSYNC_CMD 1>&2
+        eval $RSYNC_CMD  1>&2
 
-    eval $RSYNC_CMD  1>&2
-    if [ $? -eq 0 ]; then
         if [ $REPORTED_VERSION -eq 0 ]
         then
             OUTPUT_STRING="{ \"version\": { \"ref\": \"$VERSION_REF\"} }"
             echo "DEBUG: outputting $OUTPUT_STRING to concourse" 1>&2
             echo $OUTPUT_STRING
             REPORTED_VERSION=1
+            exit 0
+        fi
+
+        i=0
+
+        while [ $? -ne 0 -a $i -lt $MAX_RETRIES -a REPORTED_VERSION=0 ]
+        do
+            if [ $? -eq 0 ]; then
+                if [ $REPORTED_VERSION -eq 0 ]
+                then
+                    OUTPUT_STRING="{ \"version\": { \"ref\": \"$VERSION_REF\"} }"
+                    echo "DEBUG: outputting $OUTPUT_STRING to concourse" 1>&2
+                    echo $OUTPUT_STRING
+                    REPORTED_VERSION=1
+                fi
+            fi
+
+            echo "Command failed - retrying in $SLEEP_TIME..."
+            sleep $SLEEP_TIME
+            echo $RSYNC_CMD 1>&2
+            eval $RSYNC_CMD  1>&2
+        done
+        if [ $i -eq $MAX_RETRIES ]
+        then
+            echo "Max retries reached"
+            exit 1
         fi
     else
-        echo "Failed to rsync $SRC_DIR to $DEST_DIR" 1>&2
+        echo "Failed to create destination $DEST_DIR" 1>&2
         exit 1
-    fi
-    else
-    echo "Failed to create destination $DEST_DIR" 1>&2
-    exit 1
     fi
 done
